version: '3'
services:

  mongo:
    image: 'mongo:latest'
    
    volumes:
      - ./data:/data/db
    ports:
      - '27017'

  app:
    command: node index.js
    env_file: 
      - .env
    depends_on:
      - mongo
    restart: always
    build: .
    ports:
      - '80:3000'
