version: '3'
services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  mongo:
    image: 'mongo:latest'
    
    volumes:
      - ./data:/data/db
    ports:
      - '27017'

  app:
    command: node index.js
    environment:
      - REDIS_ADDR=redis:6379
    env_file: 
      - .env
    depends_on:
      - mongo
      - redis
    restart: always
    build: .
    ports:
      - '80:3000'
